// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    'aws_project_region': 'eu-central-1',
    'aws_cognito_identity_pool_id': 'eu-central-1:31f8bc9c-a858-4e06-bf46-2e4eaa7689b5',
    'aws_cognito_region': 'eu-central-1',
    'aws_user_pools_id': 'eu-central-1_0Jy0aVG1B',
    'aws_user_pools_web_client_id': '1inqvg36rl1lve68tcliff6n8q',
    'oauth': {},
    'aws_appsync_graphqlEndpoint': 'https://q7bb7d2snffzniuaahaqnwje3q.appsync-api.eu-central-1.amazonaws.com/graphql',
    'aws_appsync_region': 'eu-central-1',
    'aws_appsync_authenticationType': 'AMAZON_COGNITO_USER_POOLS'
};


export default awsmobile;
